### ISSUE TITLE
Error handling in CollectionsDataSource

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#128]
How to deal with failures from the server in the resolver and Datasource within Apollo.

The following error is shown if `collectionsApi` is not avaliable:

```
"stacktrace": [
            "TypeError: Cannot read property 'response' of undefined",
            "    at CollectionsRestDatasource.didEncounterError (/Users/david/development/repos/moneycol/server/src/infrastructure/collections/CollectionsRestDatasource.ts:56:36)",
            "    at CollectionsRestDatasource.<anonymous> (/Users/david/development/repos/moneycol/server/node_modules/apollo-datasource-rest/src/RESTDataSource.ts:263:16)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/Users/david/development/repos/moneycol/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:6:65)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

- When getting duplicated error creating a collection:

In the logs:

```
 Error from API undefined
```

**Comment by dfernandezm** [comment]
Done already
