### ISSUE TITLE
Fix Indexer function failing to communicate with GKE/Elastic

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/moneycol#353]
# Task

Indexer always fails with:

```
org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.lang.RuntimeException: Error authenticating against GKE at com.moneycol.indexer.infra.connectivity.gke.GkeClient.getServiceDetails(GkeClient.java:56) at com.moneycol.indexer.infra.connectivity.gke.InGkeElasticSearchDiscoveryClient.obtainEndpoint(InGkeElasticSearchDiscoveryClient.java:24) at com.moneycol.indexer.indexing.index.ElasticClientFactory.elasticSearchClient(ElasticClientFactory.java:21) at com.moneycol.indexer.indexing.index.$ElasticClientFactory$ElasticSearchClient0$Definition.build(Unknown Source) at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336) ... 58 more Caused by: java.lang.RuntimeException: Cannot find any internal address in cluster at com.moneycol.indexer.infra.connectivity.gke.GkeClient.getNodeIpByType(GkeClient.java:87) at com.moneycol.indexer.infra.connectivity.gke.GkeClient.getServiceDetails(GkeClient.java:48) ...
```

Probably the timing of indexer finishing: 

```
2022-08-14 12:12:59.526 BST
```

Does not match when the GKE cluster is up

# Acceptance criteria

- [x] Indexer is able to communicate with GKE and get the data into Elasticsearch

# Definition of Done
1. - [x] Current tests pass
2. - [x] New tests added
3. - [x] Pull Request and self review
4. - [x] Clean build

**Comment by dfernandezm** [comment]
Changing the dates for Cloud Scheduler as:

- `start-crawler` boots at 2:15am, and it takes around 10h to currently crawl all banknotes (around 12:15)
- `shrink` was done at 12:00am, quite early compared to when Indexer ran, so Indexer sees the GKE cluster stopped


GKE needs to stay up from 1.45am till 1.45pm the day this all runs. Changing it manually first to test.

<img width="1464" alt="Screenshot 2022-08-18 at 09 10 20" src="https://user-images.githubusercontent.com/5462605/185344577-da5d9ab9-ed8d-409b-8cb8-99d1f10de4f1.png">

<img width="558" alt="Screenshot 2022-08-18 at 09 11 27" src="https://user-images.githubusercontent.com/5462605/185344692-e5195d77-7bf1-41a5-9459-0d11296b83dc.png">

**Comment by dfernandezm** [comment]
Testing for the night of 19Aug - 20th Aug.

**Comment by dfernandezm** [comment]
It works, but it gives 2 main errors, that need separate issues:

`dev.moneycol.indexer.sink` subscription is not present, most likely is missing from the Terraform automation done lately and never noticed as the whole process was failing.

```
2022-08-28 12:14:32.952 BSTindexer-indexingmpy5z5imaif1 com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=dev.moneycol.indexer.sink). at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133) at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277) at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038) at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808) at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563) at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533) at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463) at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427) at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460) at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557) at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717) at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) at com.moneycol.indexer.infra.pubsub.PubSubClient.pullMessages(PubSubClient.java:209) at com.moneycol.indexer.infra.pubsub.PubSubClient.subscribeSync(PubSubClient.java:126) at com.moneycol.indexer.indexing.IndexerFunctionExecutor.execute(IndexerFunctionExecutor.java:60) at com.moneycol.indexer.indexing.IndexerFunction.accept(IndexerFunction.java:41) at com.moneycol.indexer.indexing.IndexerFunction.accept(IndexerFunction.java:29) at 
```

There was an `outOfMemoryError` too, in one of the executions:

```
2022-08-28 12:14:33.209 BSTindexer-indexingey8l1nzlt79t Function invocation was interrupted. Error: memory limit exceeded.
Function invocation was interrupted. Error: memory limit exceeded.
```

**Comment by dfernandezm** [comment]
Once a month, on the first of each:

<img width="1462" alt="Screenshot 2022-09-05 at 07 24 37" src="https://user-images.githubusercontent.com/5462605/188374104-81724a15-35c7-4f7a-bd94-a696b65ff02f.png">


- [x] Add to Terraform the cron
- [x] Create the sink subscription/topic (somehow subscription is absent)
